import React from 'react'

import styles from './BodyViewer.module.css'

const Viewer = ({ image, modelo, prompt }) => {
  const bgImage = {
    backgroundImage: `url(${image})`,
    backgroundAttachment: 'scroll',
    backgroundOrigin: 'padding-box',
    backgroundClip: 'border-box',
    backgroundPositionX: 'right',
    backgroundPositionY: 'bottom',
    backgroundSize: 'cover',
    backdropFilter: 'blur(12px)'
  }

  return (
    <div
      style={bgImage}
      className={`w-full h-full flex justify-center items-center relative ${styles.containerViewer}`}
    >
      <img
        className='object-contain z-50'
        width={500}
        height={500}
        src={image} alt={`image generated by ${modelo} with prompt ${prompt}`}
      />
    </div>
  )
}

export default Viewer
