import React from 'react'
import { FiTwitter } from 'react-icons/fi'

const DownloadButton = ({ image, modelo }) => {
  const url = window.location.href
  const text = `Image generated by ${modelo}`

  return (
    <div className='flex items-center gap-2'>
      <a className='btn btn-primary btn-sm capitalize' href={image} download target='_blank' rel='noreferrer'>Download</a>
      <a className='btn btn-primary btn-sm capitalize' href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`} target='_blank' rel='noreferrer'>
        <FiTwitter size='1.25rem' />
      </a>
    </div>
  )
}

export default DownloadButton
